/* AppObjects.h - Generated by Visual Multi-Thread Win32 */

#ifndef APPOBJECTS_H
#define APPOBJECTS_H

#define _WIN32_WINNT 0x501
#include <windows.h>

extern HANDLE ClienteSend;
extern HANDLE ClienteReceive;
extern SOCKET ClientSocket;

static volatile int keepRunning = 1;

#endif /* APPOBJECTS_H */

