/* ServerInstance.cpp - Generated by Visual Multi-Thread Win32 */

#undef UNICODE
#define WIN32_LEAN_AND_MEAN

#include <winsock2.h>
#include <ws2tcpip.h>
#include <stdlib.h>
#include <stdio.h>
#include "AppObjects.h"
#include "my_socket.h"
// Need to link with Ws2_32.lib
#pragma comment (lib, "Ws2_32.lib")

#include "AppObjects.h"

using namespace std;

DWORD WINAPI thread_ServerInstance(SOCKET *lpParameter)
{
	SOCKET Server_Socket;
	Server_Socket = *lpParameter;

	Message message;

	while (true)
	{
        char received_character;
        int length = recv(Server_Socket, (char *)&received_character, (int)sizeof(char), 0);

		if (length == 0 || length == SOCKET_ERROR) break;
		
        printf("%c", received_character);
	}

	closesocket(Server_Socket);
	return 0;
}
