/* Cliente.cpp - Generated by Visual Multi-Thread Win32 */

// WIN32_LEAN_AND_MEAN macro prevents the Winsock.h from being 
// included by the Windows.h header
#define WIN32_LEAN_AND_MEAN

// The Winsock2.h header file contains most of the Winsock functions, 
// structures, and definitions. The Ws2tcpip.h header file contains 
// definitions introduced in the WinSock 2 Protocol-Specific
// The Winsock2.h header file internally includes core elements from 
// the Windows.h header file
#include <winsock2.h>
#include <ws2tcpip.h>
#include <stdlib.h>
#include <stdio.h>
#include "AppObjects.h"
#include "my_socket.h"
#include <string>
#include <cstdio>
#include <iostream>

using namespace std;

// Need to link with Ws2_32.lib, Mswsock.lib, and Advapi32.lib
#pragma comment (lib, "Ws2_32.lib")
#pragma comment (lib, "Mswsock.lib")
#pragma comment (lib, "AdvApi32.lib")

void InitString(char* buffer, int length)
{
	for (int i = 0; i < length; i++)
	{
		buffer[i] = '\0';
	}
}

DWORD WINAPI thread_Cliente(LPVOID lpParameter);

DWORD WINAPI thread_Cliente(LPVOID lpParameter)
{
	// Create a WSADATA object called wsaData.
	WSADATA wsaData;
	SOCKET ConnectSocket = INVALID_SOCKET;
	// Declare an addrinfo object that contains a sockaddr structure 
	// and initialize these values.
	struct addrinfo *result = NULL,
		*ptr = NULL,
		hints;

	int iResult;
	int recvbuflen = DEFAULT_BUFLEN;
	message msg1;
	char scanTrash;
	char response[DEFAULT_BUFLEN];

	SocketParams *params;
	params = (SocketParams *)lpParameter;

	printf("Entre com o nome do Cliente: \n");
	gets(msg1.name);

	// Initialize Winsock  
	// The WSAStartup function is called to initiate use of WS2_32.dll
	// The MAKEWORD(2,2) parameter of WSAStartup makes a request for 
	// version 2.2 of Winsock on the system
	iResult = WSAStartup(MAKEWORD(2, 2), &wsaData);
	if (iResult != 0)
	{
		printf("WSAStartup failed with error: %d\n", iResult);
		return 1;
	}

	ZeroMemory(&hints, sizeof(hints));
	// Internet address family is unspecified so that either an 
	// IPv6 or IPv4 address can be returned. The application requests 
	// the socket type to be a stream socket for the TCP protocol
	hints.ai_family = params->family;
	hints.ai_socktype = params->socktype;
	hints.ai_protocol = params->protocol;

	/* Resolve the server address and port */
	// getaddrinfo function request the IP address for the server name and 
	// the TCP port on the server that the client will connect
	iResult = getaddrinfo(params->ip, params->port, &hints, &result);
	if (iResult != 0) {
		printf("getaddrinfo failed with error: %d\n", iResult);
		WSACleanup();
		return 1;
	}
	/* Attempt to connect to an address until one succeeds  */
	for (ptr = result; ptr != NULL; ptr = ptr->ai_next)
	{
		/* Create a SOCKET for connecting to server */
		ClientSocket = socket(ptr->ai_family, ptr->ai_socktype, ptr->ai_protocol);
		if (ClientSocket == INVALID_SOCKET)
		{
			printf("socket failed with error: %ld\n", WSAGetLastError());
			WSACleanup();
			return 1;
		}

		/* Connect to server - For a client to communicate on a network, it must connect
		   to a server. Connect function request the created socket and the sockaddr
		   structure as parameters */
		iResult = connect(ClientSocket, ptr->ai_addr, (int)ptr->ai_addrlen);
		if (iResult == SOCKET_ERROR)
		{
			closesocket(ClientSocket);
			ClientSocket = INVALID_SOCKET;
			continue;
		}
		break;
	}
	char status = 'A';
	while (status != 'f')
	{
		printf("Insert file name: ");
		gets(msg1.name);

		printf("Insert operation (1-Create, 2-Delete, 3-Read, 4-Write): ");
		scanf("%i", &msg1.nro_msg);
		scanf("%c", &scanTrash);
		if (msg1.nro_msg == 4)
		{
			printf("Insert your message: ");
			gets(msg1.buf);
		}
		else
		{
			msg1.buf[0] = '\0';
		}

		/* Client send a message to the Server */
		iResult = send(ClientSocket, (const char *)&msg1, (int)sizeof(msg1), 0);
		if (iResult == SOCKET_ERROR) {
			printf("send failed with error: %d\n", WSAGetLastError());
			closesocket(ClientSocket);
			WSACleanup();
			return 1;
		}

		printf("Client - Bytes Sent: %ld\n", iResult);

		/* Wait for a reply of the Server */
		InitString(response, DEFAULT_BUFLEN);
		iResult = recv(ClientSocket, (char *)&response, DEFAULT_BUFLEN, 0);

		printf("Client received-message: %s\n\n", response);

		Sleep(10);

		printf("Tecle: f - Para terminar ou c - Para enviar outra mensagem \n");
		status = 'A';
		while ((status != 'f') && (status != 'c'))
		{
			status = getchar();  Sleep(10);
			getchar();
		}
	}

	// Send a message	'0' to Server in order to close the connection
	msg1.buf[0] = '0';
	iResult = send(ClientSocket, (const char *)&msg1, (int)sizeof(msg1), 0);
	closesocket(ClientSocket);
	return 0;
}
