/* main.cpp - Generated by Visual Multi-Thread Win32 */

#include <winsock2.h>
#include "AppObjects.h"
#include "my_socket.h"
#define DEFAULT_PORT "5000"


extern DWORD WINAPI thread_Servidor(LPVOID lpParameter);
void main(void);

void main(void)
{
	SocketParams params;
	
	strcpy(params.port, DEFAULT_PORT);
	
	params.family = AF_INET;       // unspecified so that either an IPv6 or IPv4 address can be returned
	params.socktype = SOCK_DGRAM; // stream socket for the TCP protocol
	params.protocol= IPPROTO_UDP;	 // TCP protocol
	params.flags = AI_PASSIVE;		 // indicates the caller intends to use the returned socket address structure in a call to the bind function
	Servidor = CreateThread(0, 0,(LPTHREAD_START_ROUTINE) thread_Servidor, &params, 0, 0);
	WaitForSingleObject(Servidor, INFINITE);
}
